### ISSUE TITLE
Lab A01 issues consolidated

### ISSUE THREAD

**Issue by rabwill** [OfficeDev/TeamsAppCamp1#62]
[https://github.com/OfficeDev/TeamsAppCamp1/blob/main/Labs/Labs-A/Lab-A01.md](https://github.com/OfficeDev/TeamsAppCamp1/blob/main/Labs/Labs-A/Lab-A01.md)

Step 2 - **Enable Teams application uploads** , Add instructions for navigating to M365 admin center.

Step 2 - Missing "Save" button selection after the "Upload custom apps" toggled is turned on. The screenshot also misses the **Save** button in most cases ignored by users since it is way down the page.

**Comment by rabwill** [comment]
Exercise 3: Change "Show More" to "Show all" in the admin center's left navigation.

**Comment by rabwill** [comment]
Exercise 4: Step 1: Start ngrok

Let's add a line before running the script, that the command has to be run in the same folder where ngrok.exe is saved.

**Comment by rabwill** [comment]
Typo at like `The starting code for the "A" path is in the A01-Start-AAD folder. Copy this folder to nother ` - Another not nother :P

**Comment by rabwill** [comment]
Issue on my first login : Error 403 calling Graph in getEmployeeIdForUser: Forbidden 
The Microsoft login page keeps on glitching signing me out and asking to login again :(

**Comment by rabwill** [comment]
Step 3: Grant permissions to your application - You'll need to Grant **Admin consent** for the application or this won't work.

**Comment by BobGerman** [comment]
> Issue on my first login : Error 403 calling Graph in getEmployeeIdForUser: Forbidden
The Microsoft login page keeps on glitching signing me out and asking to login again :(

@Rabia Am I correct in assuming that's because the permissions were not granted?
I added the missing step; hoping that helps!
