### ISSUE TITLE
Use of middleware in initializeIdentityService()

### ISSUE THREAD

**Issue by rabwill** [OfficeDev/TeamsAppCamp1#93]
Move ` app.use('/api/', validateApiRequest);` to end of the function initializeIdentityService() or add a `next()` in the app.use middle ware. 
Any other routes added after app.use without a next() will not be called. Hence throwing a unauthorized error.

**Comment by BobGerman** [comment]
Fixed in PR #94 - updated the lab instructions - good catch, thank you
